version: '3'
services:
  rock-n-rate:
    container_name: rock-n-rate
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: rock-n-rate
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
